name: update-checker

on:
    workflow_dispatch:

env:
    TOKEN_PAT: ${{ secrets.TOKEN_PAT }}
    dantotsu_runs: "https://api.github.com/repos/rebelonion/Dantotsu/actions/workflows/beta.yml/runs?branch=dev"
    status: failure

jobs:
    check_for_update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Run Main.go
              id: run-main
              run: |
                go run ./src/main.go 
                echo "status=$(cat info/status.txt)" >> $GITHUB_ENV

            - name: Commit Changes
              run: |
                  git config --global user.email "${{ secrets.EMAIL }}"
                  git config --global user.name "${{ github.repository_owner }}"
                  git add .
                  git commit -m "Updated dantotsu to latest version"

            - name: Push Changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Run Release
              run: gh workflow run release.yaml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_REPO: ${{ github.repository }}
              if: ${{ env.status == 'success' }}