name: update-checker

on:
    workflow_dispatch:

env:
    TOKEN_PAT: ${{ secrets.TOKEN_PAT }}
    dantotsu_runs: "https://api.github.com/repos/rebelonion/Dantotsu/actions/workflows/beta.yml/runs?branch=dev"
    status: success
    workflow_name: unknown
    commit_log: none

jobs:
    check_for_update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Run Main.go
              run: |
                go run ./src/main.go 

                status=$(cat info/status.txt)
                workflow_name=$(cat info/workflow-name.txt)
                commit_log=$(cat info/commit_log.txt)

                echo "status=$status" >> $GITHUB_ENV
                echo "workflow_name=$workflow_name" >> $GITHUB_ENV
                echo "commit_log=$commit_log" >> $GITHUB_ENV

            - name: Get Apk Info
              id: apk-info
              uses: hkusu/apk-info-action@v1
              with:
                  apk-path: "./temp/app-google-universal-alpha.apk"
              if: ${{ env.status == 'success' }}

            - name: Commit Changes
              run: |
                  git config --global user.email "${{ secrets.EMAIL }}"
                  git config --global user.name "${{ github.repository_owner }}"
                  git add . ':!temp'
                  git commit -m "Updated dantotsu to latest version"

            - name: Push Changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish Release
              uses: softprops/action-gh-release@v2
              with:
                  files: ./temp/*.apk
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag_name: ${{ steps.apk-info.outputs.version-name }}
                  name: ${{ env.workflow_name }}
                  body: ${{ env.commit_log }}
              if: ${{ env.status == 'success' }}

    rerun-workflow:
        name: Re-run workflow
        needs: check_for_update
        if: success() || failure()
        runs-on: ubuntu-latest
        steps:
            - name: Sleep until 5 minutes have passed
              run: |
                  sleep 300

            - name: Re-trigger workflow
              run: gh workflow run checker.yaml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_REPO: ${{ github.repository }}