name: checker

on:
    schedule:
        - cron: "*/5 * * * *"
    workflow_dispatch:

jobs:
    check_workflow_id:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Compare Workflow ID
              id: compare_ids
              run: |
                  stored_workflow_id=$(cat ./temp/workflow-id.txt)
                  echo "Stored Workflow ID: $stored_workflow_id"
                  latest_workflow_info=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/rebelonion/Dantotsu/actions/workflows/beta.yml/runs?branch=dev")
                  latest_workflow_id=$(echo $latest_workflow_info | jq -r '.workflow_runs[0].id')
                  echo "Latest Workflow ID: $latest_workflow_id"
                  if [ "$stored_workflow_id" == "$latest_workflow_id" ]; then
                    echo "$stored_workflow_id" >> $GITHUB_STATE
                  else
                    echo "1" >> $GITHUB_STATE
                  fi

    run_on_change:
        needs: check_workflow_id
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Run on Change
              if: ${{ runner.workspace }}/$GITHUB_STATE == '1'
              run: echo "Workflow ID has changed"
