name: update-checker

on:
    workflow_dispatch:

env:
    TOKEN_PAT: ${{ secrets.TOKEN_PAT }}
    ids_same: 0
    start_time: 0
    duration: 0

jobs:
    check_for_update:
        runs-on: ubuntu-latest
        steps:
            - name: Record job start time
              id: start
              run: echo "start_time=$(date +%s)" >> $GITHUB_ENV

            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Compare Workflow ID
              id: compare_ids
              run: |
                  stored_workflow_id=$(cat ./temp/workflow-id.txt)
                  echo "Stored Workflow ID: $stored_workflow_id"
                  latest_workflow_info=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      "https://api.github.com/repos/rebelonion/Dantotsu/actions/workflows/beta.yml/runs?branch=dev")
                  latest_workflow_id=$(echo $latest_workflow_info | jq -r '.workflow_runs[0].id')
                  echo "Latest Workflow ID: $latest_workflow_id"
                  if [ "$stored_workflow_id" == "$latest_workflow_id" ]; then
                    echo "ids_same=0" >> $GITHUB_ENV
                  else
                    echo "ids_same=1" >> $GITHUB_ENV
                  fi

            - name: Check Workflow ID
              run: |
                  if [ $ids_same -eq 1 ]; then
                    echo "Workflow ID has changed, running main.go"
                    go run main.go
                  else
                    echo "Workflow ID has not changed"
                  fi

            - name: Get Apk Info
              id: apk-info
              uses: hkusu/apk-info-action@v1
              with:
                  apk-path: "./temp/app-google-alpha.apk"
              if: env.ids_same == 1
            - name: Commit Changes
              run: |
                  git config --global user.email "${{ secrets.EMAIL }}"
                  git config --global user.name "kaorlol"
                  git add .
                  git commit -m "Updated dantotsu to latest version"
              if: env.ids_same == 1

            - name: Push Changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
              if: env.ids_same == 1

            - name: Publish Release
              uses: softprops/action-gh-release@v2
              with:
                  files: ./temp/app-google-alpha.apk
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag_name: ${{ steps.apk-info.outputs.version-name }}-${{ github.run_id }}
                  name: Release ${{ steps.apk-info.outputs.version-name }}-${{ github.run_id }}
              if: env.ids_same == 1

            - name: Record job end time
              id: end
              run: |
                end_time=$(date +%s)
                start_time=${{ env.start_time }}
                duration=$((end_time - start_time))
                ehco duration
                echo "duration=$duration" >> $GITHUB_ENV
                echo ${{ env.duration }}

    manual-rerun:
      name: Re-run workflow
      needs: check_for_update
      if: success() || failure()
      runs-on: ubuntu-latest
      steps:
        - name: Sleep until 5 minutes have passed
          run: |
            echo ${{ env.duration }}
            sleep 300
    
        - name: Re-trigger workflow
          run: gh workflow run main.yml
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GH_REPO: ${{ github.repository }}