name: releaser

on:
  workflow_dispatch:

env:
  workflow_name: none
  apk-version: none

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Workflow Name
        run: echo "workflow_name=$(cat info/workflow-name.txt)" >> $GITHUB_ENV

      - name: Delete Old Releases
        run: |
          releases=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases | jq -r '.[] | .id' | sort -nr)

          for release in $releases; do
            curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/releases/$release
          done

      - name: Delete Old Tags
        run: |
          tags=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/tags | jq -r '.[] | .name')

          for tag in $tags; do
            curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/git/refs/tags/$tag
          done

      - name: Get Apk Version
        run: |
          version=$(cat version.txt)
          echo "apk-version=$version" >> $GITHUB_ENV

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
            files: ./temp/*.apk
            tag_name: ${{ env.apk-version }}
            name: ${{ env.workflow_name }}
            body_path: ./info/commit-log.txt
